context:
  version: 0.3.0
  python_min: "3.14"
  python_max: "3.14"

package:
  name: logic1
  version: ${{ version }}

source:
  url: https://github.com/logic1-eu/logic1/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 95f3a085ccaf56050daf14c3fc2ad20218ce3f783f46c55855eddbaa5f49a82a

build:
  number: 0
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content:
      - export CFLAGS="${CFLAGS} -I${SP_DIR}/gmpy2"
      - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - ${{ compiler('c') }}
    - cython >=3.1.0
    - gmpy2
    - pip
    - python 3.14.* *_cp314
    - setuptools
    - setuptools_scm
  run:
    - gmpy2
    - more-itertools
    - pyeda
    - python 3.14.* *_cp314
    - python-flint
    - sage
    - typing-extensions

tests:
  - script:
      - export DOT_SAGE="${PWD}/.sage"
      - python -c "import logic1"
  - script:
      - export DOT_SAGE="${PWD}/.sage"
      - python -m doctest -o NORMALIZE_WHITESPACE logic1/theories/Sets/test_qe.txt
    files:
      source:
        - logic1/theories/Sets/test_qe.txt

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Interpreted first-order logic in Python
  homepage: https://docs.logic1.eu/
  documentation: https://docs.logic1.eu/
  description: |
    First-order logic recursively builds terms from variables and a specified set of function symbols with specified arities, which includes constant symbols with arity zero. Next, atomic formulas are built from terms and a specified set of relation symbols with specified arities. Finally, first-order formulas are recursively built from atomic formulas and a fixed set of logical operators.

    Logic1 focuses on interpreted first-order logic, where the above-mentioned function and relation symbols have implicit semantics, which is not explicitly expressed via axioms within the logical framework. Typical applications include algebraic decision procedures and, more generally, quantifier elimination procedures, e.g., over the real numbers.
  repository: https://github.com/logic1-eu/logic1

extra:
  recipe-maintainers:
    - lorenzleutgeb
    - thomas-sturm
